version: "3"

tasks:
    compile:
        # method: timestamp
        method: checksum
        sources:
            - src/**/*.ts
        generates:
            - dist/**/*.js
        cmds:
            -  # rm -r dist
            - npx tsc -d --sourcemap

    webpack:
        # method: timestamp
        method: checksum
        sources:
            - src/**/*.ts
            - webpack.config.mjs
        generates:
            - dist/svgmotion.web.js
        cmds:
            - npx webpack
        deps: [compile]

    test:
        method: none
        deps: [webpack]
        cmds:
            - npm run test
    c8test:
        method: none
        deps: [webpack]
        cmds:
            - c8 npx tap -t600 --disable-coverage --reporter=terse 'test/**/*.tap.*js'

    c8html:
        method: none
        deps: [c8test]
        cmds:
            - c8 report -r html

    gen1:
        method: timestamp
        deps: [webpack]
        cmds:
            - |
                npx svgmotion gen -o /tmp/gen1.html test/gen1.js

    tapx:
        method: timestamp
        deps: [compile, webpack]
        cmds:
            - npx tap -t600 --disable-coverage --reporter=terse {{.CLI_ARGS}}

    c8html1:
        method: none
        deps: [webpack]
        cmds:
            - c8 npx tap -t600 --disable-coverage --reporter=terse {{.CLI_ARGS}}
            - c8 report -r html
    clean:
        method: none
        cmds:
            - rm -r dist

    gen.elements:
        method: checksum
        sources:
            - test/gen.node.js
        generates:
            - /tmp/elements.json
        cmds:
            - node test/gen.node.js

    find_node.j2:
        method: checksum
        deps: [gen.elements]
        sources:
            - src/model/mixins/find_node.j2.ts
            - /tmp/elements-col.json
        generates:
            - src/model/mixins/find_node.ts
        cmds:
            - python3 -m jinjagen -d /tmp/ins/elements-col.json -D / -i src/model/mixins/find_node.j2.ts -o /tmp/find_elements.ins.ts
            - python3 -m biojet1.scandir.insert src/model/mixins/ -s /tmp/ins --act

    add_elements.j2:
        method: checksum
        sources:
            - src/model/mixins/add_elements.j2.ts
            - /tmp/elements-col.json
        generates:
            - /tmp/add_elements.ts
        cmds:
            - python3 -m jinjagen -d /tmp/ins/elements-col.json -D / -i src/model/mixins/add_elements.j2.ts -o /tmp/add_elements.ins.ts
            - python3 -m biojet1.scandir.insert src/model/mixins/ -s /tmp -s /tmp/ins --act

    # fields.j2:
    #     method: checksum
    #     sources:
    #         - src/model/mixins/add_elements.j2.ts
    #         - /tmp/elements.json
    #     generates:
    #         - /tmp/add_elements.ts
    #     cmds:
    #         - env -C /mnt/META/wrx/python/flottie python3 -m tests.gen_elements || true
    #         - python3 -m jinjagen -d /tmp/ins/elements-col.json -D / -i src/model/mixins/fields.j2.ts > /tmp/fields.ts

    elements.j2:
        cmds:
            - env -C /mnt/META/wrx/python/flottie python3 -m tests.gen_elements || true
            - python3 -m jinjagen -d /tmp/ins/elements-col.json -D / -i src/model/mixins/elements.j2.ts -o /tmp/elements.ts
