version: "3"

tasks:
    compile:
        # method: timestamp
        sources:
            - src/**/*.ts
        generates:
            - dist/**/*.js
        cmds:
            - npx tsc -d --sourcemap

    webpack:
        # method: timestamp
        sources:
            - src/**/*.ts
            - webpack.config.mjs
        generates:
            - dist/svgmotion.web.js
        cmds:
            - npx webpack
        deps: [compile]

    test:
        method: none
        deps: [webpack]
        cmds:
            - npm run test

    gen1:
        method: timestamp
        deps: [webpack]
        cmds:
            - |
                npx svgmotion gen -o /tmp/gen1.html test/gen1.js
