name: Test

on:
    push:
        branches: [main, devel]
    pull_request:
        branches: [main, devel]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Cache node modules
              uses: actions/cache@v4
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}

            - run: npm i
            - run: npm i codecov c8 typescript eslint prettier opentype.js --no-save
            - run: npm run build --if-present
            - run: npm run compile
            - run: npx webpack
            - run: |
                  [ -f svgmotion.web.js ] && mv -v -t dist svgmotion.web.js
            # - run: ls dist
            # - run: ls
            - run: npm run test

            - name: tsc strict
              run: |
                  tsc -d --sourceMap --strict --noUnusedLocals --noUnusedParameters --noImplicitOverride || true

            - name: eslint
              run: |
                  eslint test/**/*.*js || true
